//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jukusui.RandomGen.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jukusui.RandomGen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   https://www.jukusui.net/Product/RandomGen/ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppInfo_AppWeb {
            get {
                return ResourceManager.GetString("AppInfo_AppWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jukusui に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppInfo_Creator {
            get {
                return ResourceManager.GetString("AppInfo_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RandomGen に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppInfo_Name {
            get {
                return ResourceManager.GetString("AppInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dice_Max {
            get {
                return ResourceManager.GetString("Dice_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Roll に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dice_Roll {
            get {
                return ResourceManager.GetString("Dice_Roll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value is Too Big に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_Bigger {
            get {
                return ResourceManager.GetString("Error_Bigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value is NOT Space Delimited に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_ListConvert {
            get {
                return ResourceManager.GetString("Error_ListConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Items are Too many に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_ListLonger {
            get {
                return ResourceManager.GetString("Error_ListLonger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value is NOT Number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NumberConvert {
            get {
                return ResourceManager.GetString("Error_NumberConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input Number or Space Delimited Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NumberOrList {
            get {
                return ResourceManager.GetString("Error_NumberOrList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value is Too Small に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_Smaller {
            get {
                return ResourceManager.GetString("Error_Smaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copied に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GenShared_Copied {
            get {
                return ResourceManager.GetString("GenShared_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grouping に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Group_Grouping {
            get {
                return ResourceManager.GetString("Group_Grouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number or Space Delimited Numbers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Group_GroupingPlaceholder {
            get {
                return ResourceManager.GetString("Group_GroupingPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Group_Input {
            get {
                return ResourceManager.GetString("Group_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Count or Space Delimited Names に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Group_InputPlaceholder {
            get {
                return ResourceManager.GetString("Group_InputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shuffle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Group_Shuffle {
            get {
                return ResourceManager.GetString("Group_Shuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Website に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_Web {
            get {
                return ResourceManager.GetString("Info_Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fonts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_Group_Font {
            get {
                return ResourceManager.GetString("License_Group_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nuget Packages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_Group_Nuget {
            get {
                return ResourceManager.GetString("License_Group_Nuget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Order_Input {
            get {
                return ResourceManager.GetString("Order_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Count or Space Delimited Names に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Order_InputPlaceholder {
            get {
                return ResourceManager.GetString("Order_InputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shuffle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Order_Shuffle {
            get {
                return ResourceManager.GetString("Order_Shuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A-Z に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Password_ChLower {
            get {
                return ResourceManager.GetString("Password_ChLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a-z に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Password_ChNumber {
            get {
                return ResourceManager.GetString("Password_ChNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Symbol に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Password_ChSymbol {
            get {
                return ResourceManager.GetString("Password_ChSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0-9 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Password_ChUpper {
            get {
                return ResourceManager.GetString("Password_ChUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Password_Generate {
            get {
                return ResourceManager.GetString("Password_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Length に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Password_Length {
            get {
                return ResourceManager.GetString("Password_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About this App に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TabName_About {
            get {
                return ResourceManager.GetString("TabName_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dice に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TabName_Dice {
            get {
                return ResourceManager.GetString("TabName_Dice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Group に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TabName_Group {
            get {
                return ResourceManager.GetString("TabName_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Info に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TabName_Info {
            get {
                return ResourceManager.GetString("TabName_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   License に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TabName_License {
            get {
                return ResourceManager.GetString("TabName_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Order に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TabName_Order {
            get {
                return ResourceManager.GetString("TabName_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TabName_Password {
            get {
                return ResourceManager.GetString("TabName_Password", resourceCulture);
            }
        }
    }
}
